version: "3"
services:
  app:
    build: .
    ports:
      - 8080:80
    restart: always
    volumes:
      - .:/var/www/html
    links:
      - mysql
      - mongo
  mysql:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33061:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=study_php
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.1
    ports:
       - 8081:80
    restart: always
    environment:
       - PMA_HOST=mysql
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_ROOT_DATABASE: blog
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
